/* tslint:disable */
/* eslint-disable */
/**
 * Participium - OpenAPI 1.0
 * Participium Server based.
 *
 * The version of the OpenAPI document: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../../generated/runtime';
import type { OfficerRole } from './OfficerRole';
import {
    OfficerRoleFromJSON,
    OfficerRoleFromJSONTyped,
    OfficerRoleToJSON,
    OfficerRoleToJSONTyped,
} from './OfficerRole';
import type { OfficeType } from './OfficeType';
import {
    OfficeTypeFromJSON,
    OfficeTypeFromJSONTyped,
    OfficeTypeToJSON,
    OfficeTypeToJSONTyped,
} from './OfficeType';

/**
 * 
 * @export
 * @interface Officer
 */
export interface Officer {
    /**
     * 
     * @type {number}
     * @memberof Officer
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Officer
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Officer
     */
    surname?: string;
    /**
     * 
     * @type {string}
     * @memberof Officer
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Officer
     */
    password?: string;
    /**
     * 
     * @type {OfficerRole}
     * @memberof Officer
     */
    role?: OfficerRole;
    /**
     * 
     * @type {OfficeType}
     * @memberof Officer
     */
    office?: OfficeType;
}



/**
 * Check if a given object implements the Officer interface.
 */
export function instanceOfOfficer(value: object): value is Officer {
    return true;
}

export function OfficerFromJSON(json: any): Officer {
    return OfficerFromJSONTyped(json, false);
}

export function OfficerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Officer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'surname': json['surname'] == null ? undefined : json['surname'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'role': json['Role'] == null ? undefined : OfficerRoleFromJSON(json['Role']),
        'office': json['Office'] == null ? undefined : OfficeTypeFromJSON(json['Office']),
    };
}

export function OfficerToJSON(json: any): Officer {
    return OfficerToJSONTyped(json, false);
}

export function OfficerToJSONTyped(value?: Officer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'surname': value['surname'],
        'email': value['email'],
        'password': value['password'],
        'Role': OfficerRoleToJSON(value['role']),
        'Office': OfficeTypeToJSON(value['office']),
    };
}

