/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Participium - OpenAPI 1.0
 * Participium Server based.
 *
 * OpenAPI spec version: 1.0.12
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name = "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface ApiResponse
 */
export interface ApiResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponse
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponse
     */
    message?: string;
}
/**
 * 
 * @export
 * @interface AuthOfficersBody
 */
export interface AuthOfficersBody {
    /**
     * 
     * @type {string}
     * @memberof AuthOfficersBody
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AuthOfficersBody
     */
    password: string;
}
/**
 * 
 * @export
 * @interface AuthOfficersBody1
 */
export interface AuthOfficersBody1 {
    /**
     * 
     * @type {string}
     * @memberof AuthOfficersBody1
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AuthOfficersBody1
     */
    password: string;
}
/**
 * 
 * @export
 * @interface AuthUsersBody
 */
export interface AuthUsersBody {
    /**
     * 
     * @type {string}
     * @memberof AuthUsersBody
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUsersBody
     */
    password: string;
}
/**
 * 
 * @export
 * @interface AuthUsersBody1
 */
export interface AuthUsersBody1 {
    /**
     * 
     * @type {string}
     * @memberof AuthUsersBody1
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUsersBody1
     */
    password: string;
}
/**
 * 
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    name?: string;
    /**
     * 
     * @type {LocationCoordinates}
     * @memberof Location
     */
    coordinates?: LocationCoordinates;
}
/**
 * 
 * @export
 * @interface LocationCoordinates
 */
export interface LocationCoordinates {
    /**
     * 
     * @type {number}
     * @memberof LocationCoordinates
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof LocationCoordinates
     */
    latitude?: number;
}
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    message: string;
}
/**
 * 
 * @export
 * @enum {string}
 */
export enum OfficeType {
    _1 = <any> 'Office 1',
    _2 = <any> 'Office 2',
    _3 = <any> 'Office 3'
}
/**
 * 
 * @export
 * @interface Officer
 */
export interface Officer {
    /**
     * 
     * @type {number}
     * @memberof Officer
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Officer
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Officer
     */
    surname?: string;
    /**
     * 
     * @type {string}
     * @memberof Officer
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Officer
     */
    password?: string;
    /**
     * 
     * @type {OfficerRole}
     * @memberof Officer
     */
    role?: OfficerRole;
    /**
     * 
     * @type {OfficeType}
     * @memberof Officer
     */
    office?: OfficeType;
}
/**
 * 
 * @export
 * @enum {string}
 */
export enum OfficerRole {
    _1 = <any> 'Role 1',
    _2 = <any> 'Role 2',
    _3 = <any> 'Role 3'
}
/**
 * 
 * @export
 * @interface Report
 */
export interface Report {
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    title?: string;
    /**
     * 
     * @type {Location}
     * @memberof Report
     */
    location?: Location;
    /**
     * 
     * @type {User}
     * @memberof Report
     */
    author?: User;
    /**
     * 
     * @type {boolean}
     * @memberof Report
     */
    anonymity?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    date?: string;
    /**
     * 
     * @type {OfficeType}
     * @memberof Report
     */
    category?: OfficeType;
    /**
     * 
     * @type {ReportDocument}
     * @memberof Report
     */
    document?: ReportDocument;
}
/**
 * 
 * @export
 * @interface ReportDocument
 */
export interface ReportDocument {
    /**
     * 
     * @type {string}
     * @memberof ReportDocument
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReportDocument
     */
    photos?: Array<string>;
}
/**
 * 
 * @export
 * @interface ReportState
 */
export interface ReportState {
    /**
     * 
     * @type {Report}
     * @memberof ReportState
     */
    report?: Report;
    /**
     * 
     * @type {State}
     * @memberof ReportState
     */
    approved?: State;
    /**
     * 
     * @type {string}
     * @memberof ReportState
     */
    reason?: string;
    /**
     * 
     * @type {Officer}
     * @memberof ReportState
     */
    officer?: Officer;
}
/**
 * 
 * @export
 * @enum {string}
 */
export enum State {
    PENDING = <any> 'PENDING',
    APPROVED = <any> 'APPROVED',
    DECLINED = <any> 'DECLINED'
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string;
}
/**
 * AuthApi - fetch parameter creator
 * @export
 */
export const AuthApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Log into the system.
         * @summary Logs officers into the system.
         * @param {AuthOfficersBody} [body] 
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginOfficer(body?: AuthOfficersBody, username?: string, password?: string, options: any = {}): FetchArgs {
            const localVarPath = `/auth/officers`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            if (username !== undefined) {
                localVarFormParams.set('username', username as any);
            }

            if (password !== undefined) {
                localVarFormParams.set('password', password as any);
            }

            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            localVarRequestOptions.body = localVarFormParams.toString();
            const needsSerialization = (<any>"AuthOfficersBody" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Log into the system.
         * @summary Logs user into the system.
         * @param {AuthUsersBody} [body] 
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser(body?: AuthUsersBody, username?: string, password?: string, options: any = {}): FetchArgs {
            const localVarPath = `/auth/users`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            if (username !== undefined) {
                localVarFormParams.set('username', username as any);
            }

            if (password !== undefined) {
                localVarFormParams.set('password', password as any);
            }

            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            localVarRequestOptions.body = localVarFormParams.toString();
            const needsSerialization = (<any>"AuthUsersBody" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Log into the system.
         * @summary Logs officers into the system.
         * @param {AuthOfficersBody} [body] 
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginOfficer(body?: AuthOfficersBody, username?: string, password?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
            const localVarFetchArgs = AuthApiFetchParamCreator(configuration).loginOfficer(body, username, password, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Log into the system.
         * @summary Logs user into the system.
         * @param {AuthUsersBody} [body] 
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser(body?: AuthUsersBody, username?: string, password?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
            const localVarFetchArgs = AuthApiFetchParamCreator(configuration).loginUser(body, username, password, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Log into the system.
         * @summary Logs officers into the system.
         * @param {AuthOfficersBody} [body] 
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginOfficer(body?: AuthOfficersBody, username?: string, password?: string, options?: any) {
            return AuthApiFp(configuration).loginOfficer(body, username, password, options)(fetch, basePath);
        },
        /**
         * Log into the system.
         * @summary Logs user into the system.
         * @param {AuthUsersBody} [body] 
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginUser(body?: AuthUsersBody, username?: string, password?: string, options?: any) {
            return AuthApiFp(configuration).loginUser(body, username, password, options)(fetch, basePath);
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * Log into the system.
     * @summary Logs officers into the system.
     * @param {AuthOfficersBody} [body] 
     * @param {string} [username] 
     * @param {string} [password] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public loginOfficer(body?: AuthOfficersBody, username?: string, password?: string, options?: any) {
        return AuthApiFp(this.configuration).loginOfficer(body, username, password, options)(this.fetch, this.basePath);
    }

    /**
     * Log into the system.
     * @summary Logs user into the system.
     * @param {AuthUsersBody} [body] 
     * @param {string} [username] 
     * @param {string} [password] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public loginUser(body?: AuthUsersBody, username?: string, password?: string, options?: any) {
        return AuthApiFp(this.configuration).loginUser(body, username, password, options)(this.fetch, this.basePath);
    }

}
/**
 * OfficersApi - fetch parameter creator
 * @export
 */
export const OfficersApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Admins create new Officer
         * @param {Officer} [body] Created user object
         * @param {number} [id] 
         * @param {string} [name] 
         * @param {string} [surname] 
         * @param {string} [email] 
         * @param {string} [password] 
         * @param {OfficerRole} [role] 
         * @param {OfficeType} [office] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOfficer(body?: Officer, id?: number, name?: string, surname?: string, email?: string, password?: string, role?: OfficerRole, office?: OfficeType, options: any = {}): FetchArgs {
            const localVarPath = `/officers`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            if (id !== undefined) {
                localVarFormParams.set('id', id as any);
            }

            if (name !== undefined) {
                localVarFormParams.set('name', name as any);
            }

            if (surname !== undefined) {
                localVarFormParams.set('surname', surname as any);
            }

            if (email !== undefined) {
                localVarFormParams.set('email', email as any);
            }

            if (password !== undefined) {
                localVarFormParams.set('password', password as any);
            }

            if (role !== undefined) {
                localVarFormParams.set('Role', role as any);
            }

            if (office !== undefined) {
                localVarFormParams.set('Office', office as any);
            }

            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            localVarRequestOptions.body = localVarFormParams.toString();
            const needsSerialization = (<any>"Officer" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Using the session key, the officer is able to retrieve the docs assigned to him.
         * @summary Retrieve Reports assigned to him
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveDocs(options: any = {}): FetchArgs {
            const localVarPath = `/officers/retrievedocs`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Report assigned to him
         * @param {number} idDoc 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewDoc(idDoc: number, options: any = {}): FetchArgs {
            // verify required parameter 'idDoc' is not null or undefined
            if (idDoc === null || idDoc === undefined) {
                throw new RequiredError('idDoc','Required parameter idDoc was null or undefined when calling reviewDoc.');
            }
            const localVarPath = `/officers/reviewdocs/{id_doc}`
                .replace(`{${"id_doc"}}`, encodeURIComponent(String(idDoc)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PATCH' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OfficersApi - functional programming interface
 * @export
 */
export const OfficersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Admins create new Officer
         * @param {Officer} [body] Created user object
         * @param {number} [id] 
         * @param {string} [name] 
         * @param {string} [surname] 
         * @param {string} [email] 
         * @param {string} [password] 
         * @param {OfficerRole} [role] 
         * @param {OfficeType} [office] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOfficer(body?: Officer, id?: number, name?: string, surname?: string, email?: string, password?: string, role?: OfficerRole, office?: OfficeType, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Officer> {
            const localVarFetchArgs = OfficersApiFetchParamCreator(configuration).createOfficer(body, id, name, surname, email, password, role, office, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Using the session key, the officer is able to retrieve the docs assigned to him.
         * @summary Retrieve Reports assigned to him
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveDocs(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Report> {
            const localVarFetchArgs = OfficersApiFetchParamCreator(configuration).retrieveDocs(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Update Report assigned to him
         * @param {number} idDoc 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewDoc(idDoc: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Report> {
            const localVarFetchArgs = OfficersApiFetchParamCreator(configuration).reviewDoc(idDoc, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * OfficersApi - factory interface
 * @export
 */
export const OfficersApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Admins create new Officer
         * @param {Officer} [body] Created user object
         * @param {number} [id] 
         * @param {string} [name] 
         * @param {string} [surname] 
         * @param {string} [email] 
         * @param {string} [password] 
         * @param {OfficerRole} [role] 
         * @param {OfficeType} [office] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOfficer(body?: Officer, id?: number, name?: string, surname?: string, email?: string, password?: string, role?: OfficerRole, office?: OfficeType, options?: any) {
            return OfficersApiFp(configuration).createOfficer(body, id, name, surname, email, password, role, office, options)(fetch, basePath);
        },
        /**
         * Using the session key, the officer is able to retrieve the docs assigned to him.
         * @summary Retrieve Reports assigned to him
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveDocs(options?: any) {
            return OfficersApiFp(configuration).retrieveDocs(options)(fetch, basePath);
        },
        /**
         * 
         * @summary Update Report assigned to him
         * @param {number} idDoc 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewDoc(idDoc: number, options?: any) {
            return OfficersApiFp(configuration).reviewDoc(idDoc, options)(fetch, basePath);
        },
    };
};

/**
 * OfficersApi - object-oriented interface
 * @export
 * @class OfficersApi
 * @extends {BaseAPI}
 */
export class OfficersApi extends BaseAPI {
    /**
     * 
     * @summary Admins create new Officer
     * @param {Officer} [body] Created user object
     * @param {number} [id] 
     * @param {string} [name] 
     * @param {string} [surname] 
     * @param {string} [email] 
     * @param {string} [password] 
     * @param {OfficerRole} [role] 
     * @param {OfficeType} [office] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficersApi
     */
    public createOfficer(body?: Officer, id?: number, name?: string, surname?: string, email?: string, password?: string, role?: OfficerRole, office?: OfficeType, options?: any) {
        return OfficersApiFp(this.configuration).createOfficer(body, id, name, surname, email, password, role, office, options)(this.fetch, this.basePath);
    }

    /**
     * Using the session key, the officer is able to retrieve the docs assigned to him.
     * @summary Retrieve Reports assigned to him
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficersApi
     */
    public retrieveDocs(options?: any) {
        return OfficersApiFp(this.configuration).retrieveDocs(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Update Report assigned to him
     * @param {number} idDoc 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OfficersApi
     */
    public reviewDoc(idDoc: number, options?: any) {
        return OfficersApiFp(this.configuration).reviewDoc(idDoc, options)(this.fetch, this.basePath);
    }

}
/**
 * ReportsApi - fetch parameter creator
 * @export
 */
export const ReportsApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all approved Reports to display on the public map
         * @summary Retrieve all public Reports for map visualization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReports(options: any = {}): FetchArgs {
            const localVarPath = `/Reports`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary User upload a new Report
         * @param {Report} [body] Created user object
         * @param {number} [id] 
         * @param {string} [title] 
         * @param {Location} [location] 
         * @param {User} [author] 
         * @param {boolean} [anonymity] 
         * @param {string} [date] 
         * @param {OfficeType} [category] 
         * @param {ReportDocument} [document] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadReport(body?: Report, id?: number, title?: string, location?: Location, author?: User, anonymity?: boolean, date?: string, category?: OfficeType, document?: ReportDocument, options: any = {}): FetchArgs {
            const localVarPath = `/Reports`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            if (id !== undefined) {
                localVarFormParams.set('id', id as any);
            }

            if (title !== undefined) {
                localVarFormParams.set('title', title as any);
            }

            if (location !== undefined) {
                localVarFormParams.set('location', location as any);
            }

            if (author !== undefined) {
                localVarFormParams.set('Author', author as any);
            }

            if (anonymity !== undefined) {
                localVarFormParams.set('Anonymity', anonymity as any);
            }

            if (date !== undefined) {
                localVarFormParams.set('Date', date as any);
            }

            if (category !== undefined) {
                localVarFormParams.set('Category', category as any);
            }

            if (document !== undefined) {
                localVarFormParams.set('Document', document as any);
            }

            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            localVarRequestOptions.body = localVarFormParams.toString();
            const needsSerialization = (<any>"Report" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReportsApi - functional programming interface
 * @export
 */
export const ReportsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get all approved Reports to display on the public map
         * @summary Retrieve all public Reports for map visualization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReports(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<Report>> {
            const localVarFetchArgs = ReportsApiFetchParamCreator(configuration).getReports(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary User upload a new Report
         * @param {Report} [body] Created user object
         * @param {number} [id] 
         * @param {string} [title] 
         * @param {Location} [location] 
         * @param {User} [author] 
         * @param {boolean} [anonymity] 
         * @param {string} [date] 
         * @param {OfficeType} [category] 
         * @param {ReportDocument} [document] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadReport(body?: Report, id?: number, title?: string, location?: Location, author?: User, anonymity?: boolean, date?: string, category?: OfficeType, document?: ReportDocument, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Report> {
            const localVarFetchArgs = ReportsApiFetchParamCreator(configuration).uploadReport(body, id, title, location, author, anonymity, date, category, document, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * ReportsApi - factory interface
 * @export
 */
export const ReportsApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Get all approved Reports to display on the public map
         * @summary Retrieve all public Reports for map visualization
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReports(options?: any) {
            return ReportsApiFp(configuration).getReports(options)(fetch, basePath);
        },
        /**
         * 
         * @summary User upload a new Report
         * @param {Report} [body] Created user object
         * @param {number} [id] 
         * @param {string} [title] 
         * @param {Location} [location] 
         * @param {User} [author] 
         * @param {boolean} [anonymity] 
         * @param {string} [date] 
         * @param {OfficeType} [category] 
         * @param {ReportDocument} [document] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadReport(body?: Report, id?: number, title?: string, location?: Location, author?: User, anonymity?: boolean, date?: string, category?: OfficeType, document?: ReportDocument, options?: any) {
            return ReportsApiFp(configuration).uploadReport(body, id, title, location, author, anonymity, date, category, document, options)(fetch, basePath);
        },
    };
};

/**
 * ReportsApi - object-oriented interface
 * @export
 * @class ReportsApi
 * @extends {BaseAPI}
 */
export class ReportsApi extends BaseAPI {
    /**
     * Get all approved Reports to display on the public map
     * @summary Retrieve all public Reports for map visualization
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsApi
     */
    public getReports(options?: any) {
        return ReportsApiFp(this.configuration).getReports(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary User upload a new Report
     * @param {Report} [body] Created user object
     * @param {number} [id] 
     * @param {string} [title] 
     * @param {Location} [location] 
     * @param {User} [author] 
     * @param {boolean} [anonymity] 
     * @param {string} [date] 
     * @param {OfficeType} [category] 
     * @param {ReportDocument} [document] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsApi
     */
    public uploadReport(body?: Report, id?: number, title?: string, location?: Location, author?: User, anonymity?: boolean, date?: string, category?: OfficeType, document?: ReportDocument, options?: any) {
        return ReportsApiFp(this.configuration).uploadReport(body, id, title, location, author, anonymity, date, category, document, options)(this.fetch, this.basePath);
    }

}
/**
 * UsersApi - fetch parameter creator
 * @export
 */
export const UsersApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This can only be done by the logged in user.
         * @summary Create user.
         * @param {User} [body] Created user object
         * @param {number} [id] 
         * @param {string} [username] 
         * @param {string} [firstName] 
         * @param {string} [lastName] 
         * @param {string} [password] 
         * @param {string} [email] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser(body?: User, id?: number, username?: string, firstName?: string, lastName?: string, password?: string, email?: string, options: any = {}): FetchArgs {
            const localVarPath = `/users`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            if (id !== undefined) {
                localVarFormParams.set('id', id as any);
            }

            if (username !== undefined) {
                localVarFormParams.set('username', username as any);
            }

            if (firstName !== undefined) {
                localVarFormParams.set('firstName', firstName as any);
            }

            if (lastName !== undefined) {
                localVarFormParams.set('lastName', lastName as any);
            }

            if (password !== undefined) {
                localVarFormParams.set('password', password as any);
            }

            if (email !== undefined) {
                localVarFormParams.set('email', email as any);
            }

            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            localVarRequestOptions.body = localVarFormParams.toString();
            const needsSerialization = (<any>"User" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Log user out of the system.
         * @summary Logs out current logged in user session.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logoutUser(options: any = {}): FetchArgs {
            const localVarPath = `/users/logout`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * This can only be done by the logged in user.
         * @summary Create user.
         * @param {User} [body] Created user object
         * @param {number} [id] 
         * @param {string} [username] 
         * @param {string} [firstName] 
         * @param {string} [lastName] 
         * @param {string} [password] 
         * @param {string} [email] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser(body?: User, id?: number, username?: string, firstName?: string, lastName?: string, password?: string, email?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<User> {
            const localVarFetchArgs = UsersApiFetchParamCreator(configuration).createUser(body, id, username, firstName, lastName, password, email, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Log user out of the system.
         * @summary Logs out current logged in user session.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logoutUser(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = UsersApiFetchParamCreator(configuration).logoutUser(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * This can only be done by the logged in user.
         * @summary Create user.
         * @param {User} [body] Created user object
         * @param {number} [id] 
         * @param {string} [username] 
         * @param {string} [firstName] 
         * @param {string} [lastName] 
         * @param {string} [password] 
         * @param {string} [email] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser(body?: User, id?: number, username?: string, firstName?: string, lastName?: string, password?: string, email?: string, options?: any) {
            return UsersApiFp(configuration).createUser(body, id, username, firstName, lastName, password, email, options)(fetch, basePath);
        },
        /**
         * Log user out of the system.
         * @summary Logs out current logged in user session.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logoutUser(options?: any) {
            return UsersApiFp(configuration).logoutUser(options)(fetch, basePath);
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * This can only be done by the logged in user.
     * @summary Create user.
     * @param {User} [body] Created user object
     * @param {number} [id] 
     * @param {string} [username] 
     * @param {string} [firstName] 
     * @param {string} [lastName] 
     * @param {string} [password] 
     * @param {string} [email] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public createUser(body?: User, id?: number, username?: string, firstName?: string, lastName?: string, password?: string, email?: string, options?: any) {
        return UsersApiFp(this.configuration).createUser(body, id, username, firstName, lastName, password, email, options)(this.fetch, this.basePath);
    }

    /**
     * Log user out of the system.
     * @summary Logs out current logged in user session.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public logoutUser(options?: any) {
        return UsersApiFp(this.configuration).logoutUser(options)(this.fetch, this.basePath);
    }

}
